### ISSUE TITLE
ImGui Definitions unfinished checklist

### ISSUE THREAD

**Issue by SirCabby** [macroquest/mq-definitions#45]
List of known unfinished imgui definitions.

I discovered this list by looking at the existing defs.  I did not attempt to find "missing" definitions, only unfinished ones.

**imgui -> datatypes -> enums:**
- [x] ImDrawFlags
- [ ] ImDrawListFlags
- [ ] ImGuiButtonFlags
- [ ] ImGuiCol
- [ ] ImGuiColorEditFlags
- [ ] ImGuiDir
- [ ] ImGuiHoveredFlags
- [ ] ImGuiMouseButton
- [ ] ImGuiPopupFlags
- [ ] ImGuiStyleVar
- [ ] ImGuiTabBarFlags
- [ ] ImGuiTabItemFlags
- [ ] ImGuiTableColumnFlags
- [ ] ImGuiTreeNodeFlags
- [ ] ImGuiViewportFlags
- [ ] ImGuiWindowFlags

**imgui -> datatypes:**
- [ ] ImColor
- [ ] ImDrawList
- [ ] ImGuiIO (contains also ImFont / ImFontAtlas)
- [ ] ImGuiListClipper
- [ ] ImGuiStyle
- [ ] ImGuiViewport
- [ ] ImVec2
- [ ] ImVec4

**ImGui.lua sections**
- [ ] Main
- [ ] Demo / Debug / Info
- [ ] Styles
- [ ] Windows
- [ ] Child Windows
- [ ] Window Utilities
- [ ] Content Region
- [ ] Windows Scrolling
- [ ] Parameters Stacks (Shared)
- [ ] Parameters Stacks (Current Window)
- [ ] Cursor / Layout
- [ ] ID Stack / Scopes
- [ ] Widgets: Text
- [ ] Widgets: Main
- [ ] Widgets: Combo Box
- [ ] Widgets: Drags
- [ ] Widgets: Sliders
- [ ] Widgets: Input with Keyboard
- [ ] Widgets: Color Editor / Picker
- [ ] Widgets: Trees
- [ ] Widgets: Selectables
- [ ] Widgets: List Boxes
- [ ] Widgets: Value() Helpers
- [ ] Widgets: Menus
- [ ] Tooltips
- [ ] Popups, Modals
- [ ] Columns
- [ ] Tab Bars, Tabs
- [ ] Docking
- [ ] Logging
- [ ] Disabling
- [ ] Clipping
- [ ] Focus, Activation
- [ ] Item / Widgets Utilities
- [ ] Viewports
- [ ] Miscellaneous Utilities
- [ ] Text Utilities
- [ ] Color Utilities
- [ ] Inputs Utilities: Keyboard
- [ ] Inputs Utilities: Mouse
- [ ] Clipboard Utilities
- [ ] Uncategorized
- [ ] Tables
- [ ] Custom additions

**Comment by brainiac** [comment]
Rather than check each thing individually, i went over the whole implementation. Everything should be present now.
